### ISSUE TITLE
Don't use an array for "preferredName"

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-authorities#9]
As resources only have one preferred name, an array isn't needed or might be confusing. Also, we don't have an array for `label` in lobid-resources so this would be consistant with our other services.

**Comment by fsteeg** [comment]
Deployed to test:

http://test.lobid.org/authorities/4074335-4.json
http://test.lobid.org/authorities/2047974-8.json
http://test.lobid.org/authorities/118540238.json

**Comment by acka47** [comment]
Looking at http://test.lobid.org/authorities/118540238.json, it probably would be consistent to also remove the array from `preferredNameEntityForThePerson`.

**Comment by fsteeg** [comment]
> it probably would be consistent to also remove the array from `preferredNameEntityForThePerson`

We'd either have to handle every type of entity (Person, Place, etc.) or change the fields to a general `preferredNameEntity` field (would that be compatible in RDF, is there a general `preferredNameEntity`? There is for `preferredName`, right?). Since our general approach is to have arrays even when only a single values occurs, I figured it would make sense to leave the `preferredNameEntityXYZ` fields as they are. What do you think, @acka47?

**Comment by acka47** [comment]
Looking at the [GND ontology](http://d-nb.info/standards/elementset/gnd), there is only `preferredNameEntityForThePerson` and no `preferredNameEntityForTheCorporateBody` etc. Thus, this shouldn't be hard to implement...

**Comment by fsteeg** [comment]
>  there is only preferredNameEntityForThePerson and no preferredNameEntityForTheCorporateBody

Oh I see, great.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/authorities/118540238.json

**Comment by acka47** [comment]
+1 Closing
